const infoLink = {
    'el-alert': 'https://element.eleme.cn/#/zh-CN/component/alert',
    'el-avatar': 'https://element.eleme.cn/#/zh-CN/component/avatar',
    'el-badge': 'https://element.eleme.cn/#/zh-CN/component/badge',
    'el-breadcrumb': 'https://element.eleme.cn/#/zh-CN/component/breadcrumb',
    'el-button': 'https://element.eleme.cn/#/zh-CN/component/button',
    'el-card': 'https://element.eleme.cn/#/zh-CN/component/card',
    'el-carousel': 'https://element.eleme.cn/#/zh-CN/component/carousel',
    'el-cascader': 'https://element.eleme.cn/#/zh-CN/component/cascader',
    'el-checkbox-group': 'https://element.eleme.cn/#/zh-CN/component/checkbox',
    'el-color-picker': 'https://element.eleme.cn/#/zh-CN/component/color-picker',
    'el-date-picker': 'https://element.eleme.cn/#/zh-CN/component/date-picker',
    'el-image': 'https://element.eleme.cn/#/zh-CN/component/image',
    'el-input': 'https://element.eleme.cn/#/zh-CN/component/input',
    'el-input-number': 'https://element.eleme.cn/#/zh-CN/component/input-number',
    'el-link': 'https://element.eleme.cn/#/zh-CN/component/link',
    'el-pagination': 'https://element.eleme.cn/#/zh-CN/component/pagination',
    'el-progress': 'https://element.eleme.cn/#/zh-CN/component/progress',
    'el-radio-group': 'https://element.eleme.cn/#/zh-CN/component/radio',
    'el-rate': 'https://element.eleme.cn/#/zh-CN/component/rate',
    'el-select': 'https://element.eleme.cn/#/zh-CN/component/select',
    'el-slider': 'https://element.eleme.cn/#/zh-CN/component/slider',
    'el-steps': 'https://element.eleme.cn/#/zh-CN/component/steps',
    'el-switch': 'https://element.eleme.cn/#/zh-CN/component/switch',
    'el-tabs': 'https://element.eleme.cn/#/zh-CN/component/tabs',
    'el-table': 'https://element.eleme.cn/#/zh-CN/component/table',
    'el-tag': 'https://element.eleme.cn/#/zh-CN/component/tag',
    'el-time-picker': 'https://element.eleme.cn/#/zh-CN/component/time-picker',
    'el-timeline': 'https://element.eleme.cn/#/zh-CN/component/timeline',
    'el-tooltip': 'https://element.eleme.cn/#/zh-CN/component/tooltip',
    'el-transfer': 'https://element.eleme.cn/#/zh-CN/component/transfer',
    'el-tree': 'https://element.eleme.cn/#/zh-CN/component/tree',
    'el-upload': 'https://element.eleme.cn/#/zh-CN/component/upload'
}

export default infoLink
